version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install App Requirements"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate --traceback
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput
      - echo "Build Stage Successful! Deploying Now!"
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
