version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - python3 -m venv env
      - chmod +x ./env/bin/activate
      - pip install --upgrade pip --disable-pip-version-check
      - pip install -r requirements.txt
  
  build:
    commands:
      - echo "Running Django migrations"
      - python manage.py migrate --traceback
      - echo "Build Stage Successful. Deploying to EBS now..."
artifacts:
  files:
    - '**/*'
